packages:
  - src/*
  - src/components/*
  - apps/*
  - packages/*
  - anchor
  - src/app/**"
catalogs:
  react16:
    react: ^16.7.0
    react-dom: ^16.7.0
  react17:
    react: ^17.10.0
    react-dom: ^17.10.0

onlyBuiltDependencies:
  - tailwindcss/oxide
  - buffer utils
  - esbuild
  - sharp
  - unrest-resolver
  - utf-8-validate
