[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "DjSdHpSGjPqWFSZuNDDFas2dVrdfrMVTir1xJgQyjLFT"
journal = "AC2NZK3Xg6HvsZdG1hc3fdWmmgqn2t9ohKHsueZacTgu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "bash -c 'echo test && echo ok done'"
test_jest = "../node_modules/.bin/jest --preset ts-jest"
test_mocha = "mocha -t 1000000 tests/"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
